### ISSUE TITLE
Reproducible Build failed

### ISSUE THREAD

**Issue by IzzySoft** [SchweGELBin/OpenBible2#14]
for v0.6.0, reproducible build failed today. APK diff:

```diff
  -rw-r--r--  0.0 unx      120 b-      118 defN 1981-01-01 01:01:02 976b62df META-INF/version-control-info.textproto
- -rw-r--r--  0.0 unx     3645 b-     3645 stor 1981-01-01 01:01:02 c932184c assets/dexopt/baseline.prof
+ -rw-r--r--  0.0 unx     3645 b-     3645 stor 1981-01-01 01:01:02 351c3e32 assets/dexopt/baseline.prof
  -rw-r--r--  0.0 unx      482 b-      482 stor 1981-01-01 01:01:02 6df1ef29 assets/dexopt/baseline.profm
- -rw-r--r--  0.0 unx  1785712 b-   857916 defN 1981-01-01 01:01:02 9276f3de classes.dex
+ -rw-r--r--  0.0 unx  1785716 b-   857873 defN 1981-01-01 01:01:02 09ac0b16 classes.dex
  -rw-r--r--  0.0 unx    10096 b-    10096 stor 1981-01-01 01:01:02 9734baa0 lib/arm64-v8a/libandroidx.graphics.path.so
```

Diff of `classes.dex`:

```diff
 |: invoke-virtual/range {v89}, LD/q;.L:()V
-|: goto/16 03ee // +038c
+|: goto/16 03f0 // +038e
 |: sget-object v5, Ll1/c;.c:LA/B;
 |: if-eqz v3, 006a // +0004
 |: move-object v6, v5
@@ -327663,7 +327663,8 @@
 |: const/4 v1, #int 0 // #0
 |: invoke-virtual {v0, v1}, LD/q;.p:(Z)V
 |: sget-object v1, Ll1/d;.a:LA/i1;
-|: and-int/lit16 v9, v4, #int 7168 // #1c00
+|: and-int/lit16 v2, v4, #int 7168 // #1c00
+|: or-int/lit16 v9, v2, #int 384 // #0180
 |: const/4 v5, #int 0 // #0
 |: move-object v4, v6
 |: move-object v6, v1
@@ -327672,7 +327673,7 @@
 |: invoke-static/range {v4, v5, v6, v7, v8, v9}, LA/b0;.a:(LA/B;LA/U0;LA/i1;LL/a;LD/q;I)V
 |: invoke-virtual/range {v89}, LD/q;.r:()LD/v0;
 |: move-result-object v6
-|: if-eqz v6, 0406 // +0014
+|: if-eqz v6, 0408 // +0014
 |: new-instance v7, Ll1/b;
```

Build is still set up with JDK-17 here, but it seems you've switched to JDK-21 – so we've tried that as well, but it didn't make a difference. Was the APK built from a clean tree at the commit the release tag points to? Something else that has changed since v0.4.0 (0.1.4 - 0.4.0 had no issues here)?

**Comment by SchweGELBin** [comment]
Hi, I just made sure to be on a clean tree (fetch & pull) and rebuild the apk.
Then I compared them and bith had the srme sha256sum.
I don't know what might have changed.
Is v0.5.0 reproducable?

**Comment by IzzySoft** [comment]
Thanks for your swift response! v0.5.0 was skipped as v0.6.0 came in before v0.5.0 could be pulled (updates only run once per day), so I cannot tell without running a build on it manually. Running that now…

Nope, that's not RB either – but that was as the APK was, according to the embedded version info, built from 4fa66c01e4dbd80cc68312bbcc435ec3d92d3a9d and not 04f2d19938d3da34d8c4b9aa74f274749c894213 as the tag indicates. When I build from the same hash, only the `AndroidManifest.xml` differs, so it *would* have been RB had it been built from a clean tree at the right commit:

```diff
-      ATTR: http://schemas.android.com/apk/res/android:versionCode=10
-      ATTR: http://schemas.android.com/apk/res/android:versionName='0.5.0'
+      ATTR: http://schemas.android.com/apk/res/android:versionCode=9
+      ATTR: http://schemas.android.com/apk/res/android:versionName='0.4.0'
```

Let me run a full diffoscope on v0.6.0, maybe that shows up which class we're talking about…

`l1/c.smali` is the only thing coming up there, sorry. Not much inside that file giving clues. I see 3 "public static final" fields, a constructor, and 1 other method. If you want to look for yourself if you can see more: [c.smali.zip](https://github.com/user-attachments/files/17821289/c.smali.zip)

**Comment by SchweGELBin** [comment]
Hmm, I'm a bit confused now.
But it could be possible that I built from the last commit before the bump twice. (Didn't know it made a difference).
To save you from more work, I released a new version and made sure to actually build if froe a clean tree: [v0.6.1](https://github.com/SchweGELBin/OpenBible2/releases/tag/v0.6.1)

**Thank you very much!**

**Comment by IzzySoft** [comment]
Wonderful, thanks!

![image](https://github.com/user-attachments/assets/29d7fd02-3a42-408d-9946-50ac147952a6)

**Comment by IzzySoft** [comment]
Hi @SchweGELBin – looks like our problem is back with v1.4.0, same diff again. Same mistake again, too?

```diff
 |: invoke-virtual/range {v89}, LC/r;.L:()V
-|: goto/16 042b // +03c9
+|: goto/16 042d // +03cb
 |: sget-object v5, Lo1/c;.c:Lz/E;
 |: if-eqz v3, 006a // +0004
 |: move-object v6, v5
@@ -433978,7 +433978,8 @@
 |: const/4 v2, #int 0 // #0
 |: invoke-virtual {v0, v2}, LC/r;.p:(Z)V
 |: sget-object v2, Lo1/d;.a:Lz/N0;
-|: and-int/lit16 v9, v4, #int 7168 // #1c00
+|: and-int/lit16 v3, v4, #int 7168 // #1c00
+|: or-int/lit16 v9, v3, #int 384 // #0180
 |: const/4 v5, #int 0 // #0
 |: move-object v4, v6
 |: move-object v6, v2
@@ -433991,7 +433992,7 @@
 |: check-cast v2, Landroid/view/View;
 |: invoke-virtual {v2}, Landroid/view/View;.isInEditMode:()Z
 |: move-result v3
-|: if-nez v3, 042b // +0031
+|: if-nez v3, 042d // +0031
 |: invoke-virtual {v2}, Landroid/view/View;.getContext:()Landroid/content/Context;
 |: move-result-object v2
 |: const-string v3, "null cannot be cast to non-null type android.app.Activity"
@@ -434001,22 +434002,22 @@
 |: move-result-object v2
 |: sget v3, Landroid/os/Build$VERSION;.SDK_INT:I
 |: const/16 v4, #int 35 // #23
-|: if-lt v3, v4, 0417 // +0008
+|: if-lt v3, v4, 0419 // +0008
 |: new-instance v3, LT0/M;
 |: invoke-direct {v3, v2}, LT0/L;.<init>:(Landroid/view/Window;)V
-|: goto 0426 // +0010
+|: goto 0428 // +0010
 |: const/16 v4, #int 30 // #1e
-|: if-lt v3, v4, 0421 // +0008
+|: if-lt v3, v4, 0423 // +0008
 |: new-instance v3, LT0/L;
 |: invoke-direct {v3, v2}, LT0/L;.<init>:(Landroid/view/Window;)V
-|: goto 0426 // +0006
+|: goto 0428 // +0006
 |: new-instance v3, LT0/K;
 |: invoke-direct {v3, v2}, LT0/K;.<init>:(Landroid/view/Window;)V
 |: xor-int/lit8 v2, v1, #int 1 // #01
 |: invoke-virtual {v3, v2}, La/a;.N:(Z)V
 |: invoke-virtual/range {v89}, LC/r;.r:()LC/x0;
 |: move-result-object v6
-|: if-eqz v6, 0443 // +0014
+|: if-eqz v6, 0445 // +0014
 |: new-instance v7, Lo1/b;
```

**Comment by SchweGELBin** [comment]
Oh, sorry. I was already a little bit curious, why the green icon didn't appear yet.

Yeah, probably the same issue, I'll rebuild it.
I have no idea, why this happens to me.

Thanks for the message.
Have a great day!

**Comment by IzzySoft** [comment]
Just attach the APK here then so I can confirm before you make a new release (and no, do not replace the APK at the current release, that has already been distributed – and we cannot replace it here either, so we'd need a new release to bring the shield up again).

You might wish to set up a Github workflow to have your (unsigned) APK built, to avoid these problems :wink:

**Comment by SchweGELBin** [comment]
I created a new release, because I needed to bump and tag it anyways.
I can still replace the new apk in the new release if the rb fails.

A GitHub workflow would really save me a lot of time. 😁

Have a great day!

**Comment by IzzySoft** [comment]
Unfortunately failed again for v1.4.1, same diff. To know what directions to go for finding the culprit, can you please let me know:

* which JDK you use (e.g. OpenJDK-17)
* which OS you build on (e.g. Debian Bookworm)
* how many CPU cores the build machine has
* any other specific settings you use (especially if they cannot be found in the repo here)

We have a few tricks in our box here, but trying them all in a row would take quite long, so narrowing things down would help. I e.g. already tried with OpenJDK 17 and 21, results are identical. I've built on Debian Bookworm, but I can easily switch to Debian Bullseye, Ubuntu 22.04 (jammy) and Ubuntu 24.04 (noble) – those are the "standard images" we use for our builders.

**Comment by SchweGELBin** [comment]
Hmm, I didn't change anything except updating android-studio.

I'm using NixOS (nixpkgs-unstable).
Android Studio: 2024.2.1
OpenJDK: 21.0.5

I rebuild the apk (v1.4.1)
[app-release.zip](https://github.com/user-attachments/files/18137975/app-release.zip)

**Comment by IzzySoft** [comment]
Has the same checksum like the one before, so same issue. Can you try building at the command line, to rule out Studio-issues? Then run `sha256sum app-release.apk`. If that gives you something other than `8e2b18b986144a61ce0b254557d129d8f402a3242b4a31c3682efb5d65d870dc` (the hash from the current one) we can give it a try here. If it gives the same, I've no clue – except that we might need to check for "flaky builds" (non-deterministic ones). As the previous runs here resulted in the very same APKs (even with JDK-17), I doubt that, though. I could try with specifying numbers of CPU cores – but you didn't answer that question…

**Comment by SchweGELBin** [comment]
Hello @IzzySoft.
Sorry for the late response.
I just created a GitHub workflow to build the apk for me.
This stops the issue to build on the wrong commit at least.

The unsigned apk from the action matches the sha256sum to the one, built from F-Droid. (Using `fdroid build com.schwegelbin.openbible`)
But The Signature isn't confirmed?

I signed via `apksigner sign --ks [path/to.keystore] app-release-unsigned.apk`.
And when I verify, it matches the AllowedAPKSigningKeys attribute. `apksigner verify --print-certs app-release-unsigned.apk`

The apk is in `v1.4.2`. I can remove the release before your repo takes it again.

**Comment by SchweGELBin** [comment]
Thanks again for all of your support!

Have a great day!

**Comment by IzzySoft** [comment]
```
BUILD SUCCESSFUL in 3m 2s
46 actionable tasks: 46 executed
+ mv app/build/outputs/apk/release/app-release-unsigned.apk /outputs/unsigned.apk

--- END BUILD LOG ---
Keeping '9ff913ce4eb934515299c3fdd081de18c68046a419f600e09bd4a71f3f5f9907-com.schwegelbin.openbible-v1.4.2-upstream.apk'...
Keeping '1cf88eac5294f1be53399894fe1a6445c3587cedf34f33371eb95cfeea3475a9-com.schwegelbin.openbible-v1.4.2-unsigned.apk'...
Reproducible: False
Tags built: 1.
```

Checking the diffs now, will then update this comment.

**Comment by IzzySoft** [comment]
From staging:

![image](https://github.com/user-attachments/assets/b9e3ca18-477a-4cc2-8a35-0c9a5ee69807)

All shields gree again :smiling_face_with_three_hearts:

**Comment by SchweGELBin** [comment]
Wow thank you very much!
